### ISSUE TITLE
Permissions don t working

### ISSUE THREAD

**Issue by mihiblu** [ItsSchatten/PortableCraftingInvs#40]
Howdy,

Permissions for: anvil, enderchest, stonecutter, loom and grindstone do not work.
Otherwise, for everything else it works, with the same method.

![image](https://user-images.githubusercontent.com/35107509/228934963-bca74da7-5b94-47de-b5fd-76ce8ae812a0.png)
![image](https://user-images.githubusercontent.com/35107509/228934864-57d5dc6d-0e1b-44bd-8a64-1731ab696e58.png)

**Comment by ItsSchatten** [comment]
Strange; thanks for the heads up! I'll take a look around and see if I can find the culprit.

**Comment by mihiblu** [comment]
Have you not found the cause yet? Because my players are looking forward to having access to the missing features.

**Comment by ItsSchatten** [comment]
I'm so sorry for the lack of response or work. I've been incredibly busy getting a project of mine up and running. I promise I shall look into in the coming few days.

**Comment by mihiblu** [comment]
Alright, thank you very much.
P.S. Good luck with the new project! Keep up the good work!

**Comment by ItsSchatten** [comment]
Hey there, would you mind sending what spigot version you are running and your plugin list? I have a hunch this may be caused by running Essentials.

**Comment by PaulinaCarrot** [comment]
Hello, having a similar issues on my server as well. This happened after updating plugins & server to 1.19.4. Here's a list of our plugins:

```
Paper Plugins:
  - Minepacks
Bukkit Plugins:
 - AuthMe, BanManager, BungeeGuard, ChatControlRed, Citizens, CMI, CMILib, CraftingStore, dynmap, Elevators
  Essentials, EssentialsGeoIP, GlobalMarketChest, GriefPrevention, HolographicDisplays, HuskSync, *JDynmapGriefPrevention, LibsDisguises, LogBlock, LuckPerms
  LWC, MaSuiteCore, MaSuiteHomes, MaSuiteTeleports, MaSuiteWarps, mcMMO, MyCommand, NashornPlus, OtherDros, PlaceholderAPI
 Plan, PortableCraftingInvs, PremiumVanish, ProtocolLib, SkinsRestorer, TAB-Bridge, TreasureChest, Vault, VillagerLobotomizatorNator, VotingPlugin
 WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, XConomy
```

**Comment by ItsSchatten** [comment]
Wonderful! Thanks a lot for that.

This confirms my theory that it's likely Essentials.

While I look into a fix or work around for this, I would highly recommend setting a custom command in the servers `commands.yml` file to point directly to PCI's command (example below), or you may pass the handling off to essentials if you prefer with their appropriate permission.


```yaml
# aliases: should replace the one already located in your commands.yml file.
aliases:
  # This will be the name of the command.
  enderchest:
  # A list of commands.
  # To make sure we are using PCI for the command handling we want to add 'portablecraftinginvs:' before the command we want to execute.
  - portablecraftinginvs:ec $1- # The $1- will pass all of the arguments in the command to PCI.
```
